[project]
name = "ungames2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "natsort>=8.4.0",
    "quart>=0.20.0",
    "uvicorn[standard]>=0.35.0",
]
