name: Ungames Docker

     
on:
  push:
    branches: [ "nightly" ]
  pull_request:
    branches: [ "nightly" ]
env:
     DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ungames2:latest
          docker build . --file Dockerfile --tag ungames2:${{ steps.date.outputs.date }}      
      - name: Push Docker image
        run: |
          docker tag ungames2:latest ${{ secrets.DOCKERHUB_USERNAME }}/ungames2:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ungames2:latest
          docker tag ungames2:${{ steps.date.outputs.date }} ${{ secrets.DOCKERHUB_USERNAME }}/ungames2:${{ steps.date.outputs.date }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ungames2:${{ steps.date.outputs.date }}
